language: python

python:
  - "2.7"

services:
  - docker

notifications:
  email: false

install:
  - curl -sL https://taskfile.dev/install.sh | sh
  - curl -sL https://releases.hashicorp.com/terraform/0.12.7/terraform_0.12.7_linux_amd64.zip -o terraform.zip
  - sudo unzip terraform.zip -d /usr/bin && rm -f terraform.zip
  - pip install pylint

script:
  - ./bin/task test build
