dist: trusty
sudo: true

language: python
python: 
  - "2.7"

services:
  - docker

before_install:
  - curl -fSL "https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
  - curl -fSL https://github.com/wata727/tflint/releases/download/v0.7.0/tflint_linux_amd64.zip -o tflint.zip
  - sudo unzip tflint.zip -d /opt/tflint
  - sudo ln -s /opt/tflint/tflint /usr/bin/tflint
  - rm -f tflint.zip
  - pip install pylint

notifications:
  email: false

script:
  - make build
