platform: linux

image_resource:
  type: docker-image
  source:
    repository: teliaoss/concourse-awscli

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_SESSION_TOKEN:

inputs:
  - name: source
  - name: terraform-out

run:
  path: source/.ci/tasks/purge-bucket/task.sh