platform: linux

image_resource:
  type: docker-image
  source:
    repository: amazonlinux
    tag: "2016.09"

inputs:
  - name: source

outputs:
  - name: built-source

run:
  path: source/.ci/tasks/build_lambdas/task.sh